---
title: "WAD TPs"
author: "Karishma Srikanth, Nada Petrovic"
date: "8/9/2022"
output: html_document

---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(imager)
library(glamr)
library(gophr)
options(scipen=999)


  load_secrets()
  msd_path <- si_path() %>% return_latest("OU_IM_FY20")
  
  #source info
  curr_pd <- source_info(msd_path, return = "period")
  curr_fy <- source_info(msd_path, return = "fiscal_year")
  mer_df <- read_msd(msd_path)
  
  WAD_KP <- mer_df %>% filter(fiscal_year == 2022,
                         str_detect(disaggregate, "KeyPop(?!\\/Status)"), #keep only KP data, eliminating duplicate disagg results for KP_PREV
                         indicator %in% c("PrEP_NEW", "TX_CURR", "KP_PREV"),
                         funding_agency == "USAID") %>% 
  select(fiscal_year, disaggregate, indicator, cumulative) %>% 
  # If cumulative=NA sets to zero
  mutate(cumulative = coalesce(cumulative, 0)) %>%
  group_by(fiscal_year, indicator) %>%
  summarise(cumulative = sum(cumulative),  .groups = 'drop') %>%
  pivot_wider(names_from = indicator, values_from = cumulative)
  
  WAD_KP_TXCURR_countries <- mer_df %>% filter(fiscal_year == 2022,
                         str_detect(disaggregate, "KeyPop(?!\\/Status)"), #keep only KP data, eliminating duplicate disagg results for KP_PREV
                         indicator %in% c("TX_CURR"),
                         funding_agency == "USAID")
  country_count<-length(unique(WAD_KP_TXCURR_countries$country))
  
  WAD_PrEP<-mer_df %>% filter(fiscal_year == 2022,
                         standardizeddisaggregate == "Age/Sex", 
                         indicator %in% c("PrEP_NEW"),
                         funding_agency == "USAID")
  
  
  ### NEXT: calculate total prep & AGYW prep ###
  
  
```

* USAID initiated more than `r format(WAD_KP$PrEP_NEW, big.mark=",")` members of key populations (KP) and XXX,XXXX adolescent girls and young women (AGYW) on Pre-Exposure Prophylaxis (PrEP) during the last year, expanding effective HIV prevention to key and priority populations. Together KP and AGYW constitute more than half of all USAID PrEP initiations, and KP and AGYW PrEP initiations grew quarter over quarter throughout the entire year [DOUBLE CHECK].

* This year alone, more than `r format(WAD_KP$TX_CURR, big.mark=",")` members of key populations in `r country_count` countries are receiving life-saving HIV medication through USAID support.

* This year USAID and our partners supported 1 million members of key populations, including sex workers, transgender people, men who have sex with men, and people who inject drugs, with HIV services and supportive interventions that improve their lives and those of their children.

* In the last two years, USAID has initiated over 1 million people across 34 countries onto pre-exposure prophylaxis (PrEP) for HIV prevention.

